DROP DATABASE IF EXISTS recipe_db;

CREATE DATABASE recipe_db;
USE recipe_db;

CREATE TABLE dishes(
id INTEGER NOT NULL AUTO_INCREMENT,
dishName VARCHAR(30) NOT NULL,
recipe VARCHAR(1000) NOT NULL,
ingredients VARCHAR(1000) NOT NULL,
country VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE users(
id INTEGER NOT NULL,
displayName VARCHAR(30),
FOREIGN KEY(dishes_id) REFERENCES users(id)
);
